// <auto-generated />
using System;
using HRMS_BackEnd.Database.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMS_BackEnd.Migrations
{
    [DbContext(typeof(HrmsDbContext))]
    [Migration("20250304182228_Initial Migration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.AttendanceRecord", b =>
                {
                    b.Property<int>("AttendanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("AttendanceID");

                    b.Property<DateOnly>("AttendanceDate")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("CheckInTime")
                        .HasColumnType("TEXT");

                    b.Property<TimeOnly?>("CheckOutTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeID");

                    b.Property<string>("Remarks")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("AttendanceId")
                        .HasName("PK__Attendan__8B69263C465BE694");

                    b.HasIndex("EmployeeId");

                    b.ToTable("AttendanceRecords");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.Benefit", b =>
                {
                    b.Property<int>("BenefitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("BenefitID");

                    b.Property<string>("BenefitName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("EligibilityCriteria")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.HasKey("BenefitId")
                        .HasName("PK__Benefits__5754C53A43825648");

                    b.ToTable("Benefits");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("DepartmentId")
                        .HasName("PK__Departme__B2079BCD3532E667");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeID");

                    b.Property<int?>("DepartmentId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DepartmentID");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("HireDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Position")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int?>("RoleId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoleID");

                    b.HasKey("EmployeeId")
                        .HasName("PK__Employee__7AD04FF130126BFC");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("RoleId");

                    b.HasIndex(new[] { "Email" }, "UQ__Employee__A9D1053434A7E8B9")
                        .IsUnique();

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.EmployeeBenefit", b =>
                {
                    b.Property<int>("EmployeeBenefitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeBenefitID");

                    b.Property<int>("BenefitId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("BenefitID");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeID");

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.HasKey("EmployeeBenefitId")
                        .HasName("PK__Employee__62EF72785015C1BC");

                    b.HasIndex("BenefitId");

                    b.HasIndex("EmployeeId");

                    b.ToTable("EmployeeBenefits");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.EmployeeTraining", b =>
                {
                    b.Property<int>("EmployeeTrainingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeTrainingID");

                    b.Property<DateOnly?>("CompletionDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeID");

                    b.Property<DateOnly>("EnrollmentDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("TrainingProgramId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("TrainingProgramID");

                    b.HasKey("EmployeeTrainingId")
                        .HasName("PK__Employee__0D6E904AFEC604FD");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("TrainingProgramId");

                    b.ToTable("EmployeeTrainings");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.Evaluation", b =>
                {
                    b.Property<int>("EvaluationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("EvaluationID");

                    b.Property<string>("Comments")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeID");

                    b.Property<DateOnly>("EvaluationDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Evaluator")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Score")
                        .HasColumnType("INTEGER");

                    b.HasKey("EvaluationId")
                        .HasName("PK__Evaluati__36AE68D30E9276C9");

                    b.HasIndex("EmployeeId");

                    b.ToTable("Evaluations");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.LeaveRequest", b =>
                {
                    b.Property<int>("LeaveRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("LeaveRequestID");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("EmployeeID");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("LeaveType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("LeaveRequestId")
                        .HasName("PK__LeaveReq__6094218EC1950229");

                    b.HasIndex("EmployeeId");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("RoleID");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("RoleId")
                        .HasName("PK__Roles__8AFACE3A4619C3D8");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.RolesChangeRequest", b =>
                {
                    b.Property<int>("RolesChangeRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("NewRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OldRoleId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("RequestDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("TEXT");

                    b.HasKey("RolesChangeRequestId")
                        .HasName("PK__RolesCha__8B3E6A5F6C68D952");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("NewRoleId");

                    b.HasIndex("OldRoleId");

                    b.ToTable("RolesChangeRequest", (string)null);
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.TrainingProgram", b =>
                {
                    b.Property<int>("TrainingProgramId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("TrainingProgramID");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProgramName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("TEXT");

                    b.HasKey("TrainingProgramId")
                        .HasName("PK__Training__4F897ABDA519765A");

                    b.ToTable("TrainingPrograms");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.AttendanceRecord", b =>
                {
                    b.HasOne("HRMS_BackEnd.Database.Models.Employee", "Employee")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_AttendanceRecord_Employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.Employee", b =>
                {
                    b.HasOne("HRMS_BackEnd.Database.Models.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentId")
                        .HasConstraintName("FK_Department");

                    b.HasOne("HRMS_BackEnd.Database.Models.Role", "Role")
                        .WithMany("Employees")
                        .HasForeignKey("RoleId")
                        .HasConstraintName("FK_Role");

                    b.Navigation("Department");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.EmployeeBenefit", b =>
                {
                    b.HasOne("HRMS_BackEnd.Database.Models.Benefit", "Benefit")
                        .WithMany("EmployeeBenefits")
                        .HasForeignKey("BenefitId")
                        .IsRequired()
                        .HasConstraintName("FK_Benefit");

                    b.HasOne("HRMS_BackEnd.Database.Models.Employee", "Employee")
                        .WithMany("EmployeeBenefits")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Employee");

                    b.Navigation("Benefit");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.EmployeeTraining", b =>
                {
                    b.HasOne("HRMS_BackEnd.Database.Models.Employee", "Employee")
                        .WithMany("EmployeeTrainings")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeTraining_Employee");

                    b.HasOne("HRMS_BackEnd.Database.Models.TrainingProgram", "TrainingProgram")
                        .WithMany("EmployeeTrainings")
                        .HasForeignKey("TrainingProgramId")
                        .IsRequired()
                        .HasConstraintName("FK_EmployeeTraining_Training");

                    b.Navigation("Employee");

                    b.Navigation("TrainingProgram");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.Evaluation", b =>
                {
                    b.HasOne("HRMS_BackEnd.Database.Models.Employee", "Employee")
                        .WithMany("Evaluations")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_Evaluation_Employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.LeaveRequest", b =>
                {
                    b.HasOne("HRMS_BackEnd.Database.Models.Employee", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK_LeaveRequest_Employee");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.RolesChangeRequest", b =>
                {
                    b.HasOne("HRMS_BackEnd.Database.Models.Employee", "Employee")
                        .WithMany("RolesChangeRequests")
                        .HasForeignKey("EmployeeId")
                        .IsRequired()
                        .HasConstraintName("FK__RolesChan__Emplo__02FC7413");

                    b.HasOne("HRMS_BackEnd.Database.Models.Role", "NewRole")
                        .WithMany("RolesChangeRequestNewRoles")
                        .HasForeignKey("NewRoleId")
                        .IsRequired()
                        .HasConstraintName("FK__RolesChan__NewRo__04E4BC85");

                    b.HasOne("HRMS_BackEnd.Database.Models.Role", "OldRole")
                        .WithMany("RolesChangeRequestOldRoles")
                        .HasForeignKey("OldRoleId")
                        .IsRequired()
                        .HasConstraintName("FK__RolesChan__OldRo__03F0984C");

                    b.Navigation("Employee");

                    b.Navigation("NewRole");

                    b.Navigation("OldRole");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.Benefit", b =>
                {
                    b.Navigation("EmployeeBenefits");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.Employee", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("EmployeeBenefits");

                    b.Navigation("EmployeeTrainings");

                    b.Navigation("Evaluations");

                    b.Navigation("LeaveRequests");

                    b.Navigation("RolesChangeRequests");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.Role", b =>
                {
                    b.Navigation("Employees");

                    b.Navigation("RolesChangeRequestNewRoles");

                    b.Navigation("RolesChangeRequestOldRoles");
                });

            modelBuilder.Entity("HRMS_BackEnd.Database.Models.TrainingProgram", b =>
                {
                    b.Navigation("EmployeeTrainings");
                });
#pragma warning restore 612, 618
        }
    }
}
